SET @QUEST_RECLAIMED_RATIONS := 12827;
SET @QUEST_AMPLE_INSPIRATION := 12828;
SET @QUEST_EXPRESSION_OF_GRATITUDE := 12836;
UPDATE `quest_template` SET `PrevQuestId`=0, `NextQuestId`=@QUEST_AMPLE_INSPIRATION, `ExclusiveGroup`=-@QUEST_EXPRESSION_OF_GRATITUDE WHERE `id`=@QUEST_EXPRESSION_OF_GRATITUDE;
UPDATE `quest_template` SET `PrevQuestId`=0, `NextQuestId`=@QUEST_AMPLE_INSPIRATION, `ExclusiveGroup`=-@QUEST_EXPRESSION_OF_GRATITUDE WHERE `id`=@QUEST_RECLAIMED_RATIONS;
