SET @QUEST_DISRUPT_THE_ATTACKS := 871;
SET @QUEST_THE_DISRUPTION_ENDS := 872;
SET @QUEST_SUPPLIES_FOR_THE_CROSSROADS := 5041;
UPDATE `quest_template` SET `PrevQuestId`=0 WHERE `Id`=@QUEST_SUPPLIES_FOR_THE_CROSSROADS;
UPDATE `quest_template` SET `PrevQuestId`=@QUEST_DISRUPT_THE_ATTACKS WHERE `Id`=@QUEST_THE_DISRUPTION_ENDS;
