DROP TABLE IF EXISTS `log_auction_house`;
CREATE TABLE `log_auction_house` (
	`date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`auctionId` INT(11) UNSIGNED NOT NULL,
	`playerGuid` INT(11) UNSIGNED NOT NULL,
	`itemEntry` INT(11) UNSIGNED NOT NULL,
	`itemGuid` INT(11) UNSIGNED NOT NULL,
	`itemCount` INT(11) UNSIGNED NOT NULL,
	`action` INT(11) UNSIGNED NOT NULL,
	`bid` INT(11) UNSIGNED NOT NULL,
	`buyout` INT(11) UNSIGNED NOT NULL,
	`comment` TEXT NULL DEFAULT NULL
)

