DROP TABLE IF EXISTS `solo_queue`;
CREATE TABLE IF NOT EXISTS `solo_queue` (
  `soloQueueId` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `soloQueueName` TEXT NOT NULL,
  `ownerGuid` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `playerClass` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `talentsSpecialization` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `backgroundColor` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `emblemStyle` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `emblemColor` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `borderStyle` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `borderColor` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `rating` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `weekGames` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `weekWins` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `seasonGames` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `seasonWins` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `rank` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `personalRating` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `matchMakerRating` INT(10) UNSIGNED NOT NULL DEFAULT '0'
) ENGINE=INNODB DEFAULT CHARSET=utf8;