# output generic information about the core and buildtype chosen
message(STATUS "")
message(STATUS "----------- SUNWELL OPTIONS: -----------")
message(STATUS "  SunwellCore revision   : ${rev_hash} ${rev_date}")
if( UNIX )
  message(STATUS "  SunwellCore buildtype  : ${CMAKE_BUILD_TYPE}")
endif()
message(STATUS "")

# output information about installation-directories and locations

message(STATUS "  Install core to        : ${CMAKE_INSTALL_PREFIX}")
if( UNIX )
  message(STATUS "  Install libraries to   : ${LIBSDIR}")
  message(STATUS "  Install configs to     : ${CONF_DIR}")
endif()
message(STATUS "")

# Show infomation about the options selected during configuration

if( SERVERS )
  message(STATUS "  Build world            : Yes (default)")
else()
  message(STATUS "  Build world            : No")
endif()

if( AUTHSERVER )
  message(STATUS "  Build authserver       : Yes")
  message(WARNING " *** AUTHSERVER - WARNING!")
  message(WARNING " *** Authserver in this project is no longer supported.")
  message(WARNING " *** You may build it, but its behaviour may differ from live version.")
  message(WARNING " *** Option left for simplified local testing.")
else()
  message(STATUS "  Build authserver       : No  (default)")
endif()

if( SCRIPTS )
  message(STATUS "  Build with scripts     : Yes (default)")
  add_compile_definitions("SCRIPTS")
else()
  message(STATUS "  Build with scripts     : No")
endif()

if( TOOLS )
  message(STATUS "  Build map/vmap tools   : Yes")
  add_compile_definitions("NO_CORE_FUNCS")
else()
  message(STATUS "  Build map/vmap tools   : No  (default)")
endif()

if( USE_COREPCH )
  message(STATUS "  Build core w/PCH       : Yes (default)")
else()
  message(STATUS "  Build core w/PCH       : No")
endif()

if( USE_SCRIPTPCH )
  message(STATUS "  Build scripts w/PCH    : Yes (default)")
else()
  message(STATUS "  Build scripts w/PCH    : No")
endif()

if( WITH_WARNINGS )
  message(STATUS "  Show all warnings      : Yes")
else()
  message(STATUS "  Show compile-warnings  : No  (default)")
endif()

if( WITH_COREDEBUG )
  message(STATUS "  Use coreside debug     : Yes")
  add_compile_definitions("TRINITY_DEBUG")
  set(CMAKE_BUILD_TYPE "Debug")
else()
  message(STATUS "  Use coreside debug     : No  (default)")
endif()

if( ADDRESS_SANITIZER )
  message(STATUS "  Use Address Sanitizer  : Yes")
else()
  message(STATUS "  Use Address Sanitizer  : No  (default)")
endif()

if( THREAD_SANITIZER )
  message(STATUS "  Use Thread Sanitizer  : Yes")
else()
  message(STATUS "  Use Thread Sanitizer  : No  (default)")
endif()

if( WITH_PROFILER )
  message(STATUS "  Use Easy Profiler  : Yes")
  add_compile_definitions("WITH_PROFILER")
else()
  message(STATUS "  Use Easy Profiler  : No  (default)")
endif()

if( NOT WITH_SOURCE_TREE STREQUAL "no" )
  message(STATUS "  Show source tree       : Yes (${WITH_SOURCE_TREE})")
else()
  message(STATUS "  Show source tree       : No")
endif()

if( WIN32 )
  if( USE_MYSQL_SOURCES )
    message(STATUS "  Use MySQL sourcetree   : Yes (default)")
  else()
    message(STATUS "  Use MySQL sourcetree   : No")
  endif()
endif( WIN32 )

if ( WITHOUT_GIT )
  message(STATUS "  Use GIT revision hash  : No")
  message(WARNING " *** WITHOUT_GIT - WARNING!")
  message(WARNING " *** By choosing the WITHOUT_GIT option you have waived all rights for support,")
  message(WARNING " *** and accept that or all requests for support or assistance sent to the core")
  message(WARNING " *** developers will be rejected. This due to that we will be unable to detect")
  message(WARNING " *** what revision of the codebase you are using in a proper way.")
  message(WARNING " *** We remind you that you need to use the repository codebase and a supported")
  message(WARNING " *** version of git for the revision-hash to work, and be allowede to ask for")
  message(WARNING " *** support if needed.")
else()
  message(STATUS "  Use GIT revision hash  : Yes (default)")
endif()

if ( NOJEM )
  message(STATUS "  Use jemalloc           : No")
  message(WARNING " *** NOJEM - WARNING!")
  message(WARNING " *** jemalloc linking has been disabled!")
  message(WARNING " *** Please note that this is for DEBUGGING WITH VALGRIND only!")
  message(WARNING " *** DO NOT DISABLE IT UNLESS YOU KNOW WHAT YOU'RE DOING!")
else()
  message(STATUS "  Use jemalloc           : Yes (default)")
endif()

if(BOOST_STATIC)
  message(STATUS "  Use Boost static libs  : Yes")
else()
  message(STATUS "  Use Boost static libs  : No  (default)")
endif()

if (DISABLE_DRESSNPCS_CORESOUNDS)
  message(STATUS "")
  message(STATUS "  DressNPCs sound workaround disabled. Live without sounds or use a client side patch.")
  add_compile_definitions("DISABLE_DRESSNPCS_CORESOUNDS")
endif()

message(STATUS "---------- END SUNWELL OPTIONS ---------")
message(STATUS "")

