DROP TABLE IF EXISTS `mythic_states`;
DROP TABLE IF EXISTS `mythic_map_data`;
DROP TABLE IF EXISTS `character_mythic_key_levels`;

CREATE TABLE IF NOT EXISTS `mythic_states`
(
	`StateType` INT UNSIGNED NOT NULL DEFAULT 0 PRIMARY KEY,
	`StateValue` VARCHAR(100) NOT NULL DEFAULT ""
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `mythic_map_data`
(
	`MapId` INT(4) UNSIGNED NOT NULL DEFAULT 0,
	`KeyLevel` INT(2) UNSIGNED NOT NULL DEFAULT 1,
	`TimeType` INT UNSIGNED NOT NULL DEFAULT 0,
	`TimeValue` INT UNSIGNED NOT NULL DEFAULT 60000,
	`TimeHolders` VARCHAR(70) DEFAULT "" COMMENT 'Player names, seperated by semicolon',
	PRIMARY KEY (MapId, KeyLevel, TimeType)
	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `character_mythic_key_levels`
(
	`PlayerGUID` INT(10) UNSIGNED NOT NULL DEFAULT 0 PRIMARY KEY,
	`KeyLevel` MEDIUMINT(8) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

